<?php
declare(strict_types=1);

namespace App\Controller;

class FAQController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        /*
        const faqs = document.querySelectorAll(".faq");

        faqs.foreach(faq => {
            faq.addEventListener("click", function() {
                faq.classList.toggle("active");
            })
    })
            */
    }

    /**
     * @return void
     */
    public function questions() {
        $this->viewBuilder()->setLayout('default');
    }
}
